### ISSUE TITLE
TCP socket is not opened (pygame simulation)

### ISSUE THREAD

**Issue by 3isenHeiM** [TUDelft-CNS-ATM/bluesky#126]
If I start an pygame simulation using ``python BlueSky.py``, it should listen on port 8888 for incoming console connections.
I cannot open a connection on this port using telnet, netcat or whatever...

Is this feature enabled with the ``pygame`` simulation ? I can't find any indication in the code.

Thanks for the support !

**Comment by jooste** [comment]
Hi!

The telnet connection is not implemented in the pygame version of BlueSky. It is technically possible, but isn't something we are planning for the pygame version. In fact, the telnet connection will be replaced by a more versatile client connection implementation based on zeromq (see the bluesky-zmq branch). What would you like to use the connection for, and why with the pygame version?

Cheers,
Joost

**Comment by vonStauffenFeld** [comment]
Ok, that's what I had supposed....

The telnet connection was just to be able to send commands remotely on a host running the application (eg for a room with multiple workstations and 1 teacher).

We use the pygame version because we're running BlueSky in virtual machines with no acceleration available for OpenGL...

Thanks for the quick reply !

**Comment by jooste** [comment]
We discussed the plain telnet functionality in a recent BlueSky workshop, and concluded that when necessary, we can implement one in a plugin. An added benefit of this implementation is that it will probably also easily work in the pygame version of BlueSky. I'll have a look at this.
