### ISSUE TITLE
Bug: valid commanded SPD not reached in all cases

### ISSUE THREAD

**Issue by RubenJacobse** [TUDelft-CNS-ATM/bluesky#210]
Aircraft do not always follow the SPD instruction as commanded but often end up with a speed that is ~1 knot different (or at least results in a value that is rounded in the wrong direction). This seems to be caused by the acceleration threshold in the `traf.UpdateAirSpeed()` method:

`need_ax = np.abs(delta_spd) > kts # small threshold`

Using a smaller threshold seems to mitigate the problem (at least to such extent that the aircraft label and pos command info display the correct speed):

`need_ax = np.abs(delta_spd) > 0.1 * kts # smaller threshold`

**Comment by ProfHoekstra** [comment]
Thanks. Will have a look. Smaller threshold is easiest but may not be best solution: We also want to avoid instabilities during large time steps.

Could also be rounding error (int vs round) in displaying, guidance or elsewhere.

Met vriendelijke groeten,
    Jacco Hoekstra


On 30 Sep 2019, at 17:28, Ruben Jacobse <notifications@github.com<mailto:notifications@github.com>> wrote:


Aircraft do not always follow the SPD instruction as commanded but often end up with a speed that is ~1 knot different (or at least results in a value that is rounded in the wrong direction). This seems to be caused by the acceleration threshold in the traf.UpdateAirSpeed() method:

need_ax = np.abs(delta_spd) > kts # small threshold

Using a smaller threshold seems to mitigate the problem (at least to such extent that the aircraft label and pos command info display the correct speed):

need_ax = np.abs(delta_spd) > 0.1 * kts # smaller threshold

**Comment by jooste** [comment]
Hi Ruben,

We've had similar problems with hdg select. I've applied the same fix to speed, see commit 1a16822.
