### ISSUE TITLE
Error in server.py

### ISSUE THREAD

**Issue by MTMesfum** [TUDelft-CNS-ATM/bluesky#211]
Hi,

There is an error propping up on 2 TU Delft Desktops which I use to run several sets of BlueSky simulations.
This is the error that shows up:

![image](https://user-images.githubusercontent.com/46937551/66400720-49b52600-e9e2-11e9-96d0-fc5d9d81bd9f.png)

It's something that has started to pop up on both machines within the last 2 weeks.
I've been using these desktops for months without seeing this problem.
What's the background of this problem?

Currently, I can run about 20 BlueSky simulations and after that it fails.
Both machines do fail around the same time, so it might be network related.
I started the latest run on Friday around 19h00. 
And on Saturday, between 09:15 and 10:00, they ended up both crashing.
The same simulation hasn't shown this type of behaviour on my desktop at home.
However, I haven't run it as extensively yet.

This is just a hunch, so I would appreciate some leads to the source of the problem.

Kind regards,

Johannes

**Comment by MTMesfum** [comment]
Hi Joost,

This is what's printed now:

![image](https://user-images.githubusercontent.com/46937551/66571359-629f1200-eb6f-11e9-895e-1d65e20d2884.png)

**Comment by jooste** [comment]
Hi Johannes,

It looks like some process other than bluesky has connected on one of the event ports of your bluesky. If it sends data on this port this obviously leads to unparseable messages. Bluesky currenly doesn't do any handshaking on first connect, this may fix things. An easy fix for you is to change the ports that bluesky uses to communicate.

In settings.cfg, these are: `event_port`, `stream_port`, `simevent_port`, and `simstream_port`.

Your error is caused by an unwanted connection on one of the event ports.

**Comment by MTMesfum** [comment]
Hi Joost,

I believe there were problems with the TU Delft network on my machines.
Someone from ICT helped and resolved some network problems.
This should fix my crashes.
Thanks for the troubleshooting.
It was very helpful.

Kind regards,

Johannes
