### ISSUE TITLE
Get Sim Infomation

### ISSUE THREAD

**Issue by Ellislee1** [TUDelft-CNS-ATM/bluesky#220]
Is there a way to get a list of all aircraft when writing a plugin as well as all current conflict warnings?

**Comment by jooste** [comment]
Yes that's definitely possible. You can access the different data objects in BlueSky by importing them (from bluesky import traf, sim, stack, ...). For more information about these objects you can also have a look at the [wiki](https://github.com/TUDelft-CNS-ATM/bluesky/wiki/API-Reference).

For instance, aircraft id's are here:

    bluesky.traf.id (a python list of strings)

and conflict state per aircraft is here:

    bluesky.traf.asas.inconf  (a boolean array)

For conflict information, note that the api will change a little soon: instead of `bluesky.traf.asas` you will have to look in `bluesky.traf.cd`. You will also be able to subclass Conflict Detection and Conflict Resolution implementations in a plugin.

**Comment by ProfHoekstra** [comment]
And by the way, you can use the bs.traf.id2idx(txt) function to quickly find the id for a given call sign(= a/c id or acid as it’s often called within BlueSky).

Be aware that over different time steps these indices may change due to deletion of traffic, so to save something by keeping the id’s is safer than keeping indices. (Or you have to make your arrays also dynamic which is slightly more complex).

Best regards,
    Jacco Hoekstra


On 23 Jan 2020, at 09:28, Joost Ellerbroek <notifications@github.com> wrote:

﻿

Yes that's definitely possible. You can access the different data objects in BlueSky by importing them (from bluesky import traf, sim, stack, ...). For more information about these objects you can also have a look at the wiki<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_TUDelft-2DCNS-2DATM_bluesky_wiki_API-2DReference&d=DwMCaQ&c=XYzUhXBD2cD-CornpT4QE19xOJBbRy-TBPLK0X9U2o8&r=5JxzVuDw_d0JV-kYyto54d3K2zKNIvniSIeVeSDtif4&m=KSHkXU4HF8HIJwfUGHL5faQa3c-sGhHc6xv6W8ml2uA&s=xRe1_HUdsw-wyS_W7mQT-qZIA3x67uuKIjAC63ZZIOA&e=>.

For instance, aircraft id's are here:

bluesky.traf.id (a python list of strings)


and conflict state per aircraft is here:

bluesky.traf.asas.inconf  (a boolean array)


For conflict information, note that the api will change a little soon: instead of bluesky.traf.asas you will have to look in bluesky.traf.cd. You will also be able to subclass Conflict Detection and Conflict Resolution implementations in a plugin.
