### ISSUE TITLE
Initialize client from code and use the gui

### ISSUE THREAD

**Issue by davidaranega** [TUDelft-CNS-ATM/bluesky#256]
Hi guys, I am doing a project where I use bluesky to run air traffic simulations. The project is about conflict resolution using reinforcement learing techniques. I would like to know if it is possible to run bluesky in the bluesky --sim mode and to visualize the interface for debuggin porpuses. So is it possible to initialize a client from code and use the gui?

Thank you in advance!

**Comment by jooste** [comment]
Hi David,

I'm not entirely sure I know what you mean :) Just so that we are using the same terminology, bluesky consists of three parts:

- sim/node: an instance of python running a single simulation.
- server: an instance of python running the communication layer between all simulation processes and all client processes (and potentially also other server processes on different computers)
- client: bluesky's GUI, but external apps connecting to bluesky to stream simulation data / send commands are also clients.

By default (when you start bluesky with `python BlueSky.py` without arguments), the GUI client and the server are started in a single python process. You can also choose to start the bluesky server in headless mode (`--headless`). This way the GUI is not started. You can connect to this server with the default gui with the following command: `python BlueSky.py --client`.

Also relevant for RL implementations: you can also import bluesky in other code, and run a simulation with a custom/external simulation loop. You might even be able to do this and still keep the sim/server connection intact, thus still allowing visual inspection using the client GUI.

Hope this helps!

**Comment by davidaranega** [comment]
Hi! 

Thanks for the response, it has helped me to clarify how the process works. At the end I managed to achieve what I was looking for.
Thank you again!
