### ISSUE TITLE
How to manually increment timestep of simulation?

### ISSUE THREAD

**Issue by epaulz-vt** [TUDelft-CNS-ATM/bluesky#265]
Hello,

I am writing a custom reinforcement learning plugin with PyTorch and have what I hope is a simple question... I would like to define my own "step" function for my training agent, so that it can perform an action based on its observed environment and then control the number of timesteps before the next observation.  This way, I can calculate an accurate reward for the model.  I have not been able to find a great way to do this without causing the simulation to crash/freeze.  Perhaps I could just track the number of timesteps elapsed between observations, but I would prefer to manually force the simulation to move forward from my plugin.

Hope this makes sense.  Any feedback would be very helpful.  Thanks!

Eric

**Comment by ProfHoekstra** [comment]
Dear Eric,

You could make sure your update function is called every time step (dt=0.05) and then count the number of steps in that function. And then decide whether you want to call any other functions of your plugin or continue the sim undisturbed. This should have the same effect.

Best regards,
    Jacco Hoekstra


On 24 Mar 2021, at 19:39, epaulz-vt ***@***.***> wrote:

﻿

Hello,

I am writing a custom reinforcement learning plugin with PyTorch and have what I hope is a simple question... I would like to define my own "step" function for my training agent, so that it can perform an action based on its observed environment and then control the number of timesteps before the next observation. This way, I can calculate an accurate reward for the model. I have not been able to find a great way to do this without causing the simulation to crash/freeze. Perhaps I could just track the number of timesteps elapsed between observations, but I would prefer to manually force the simulation to move forward from my plugin.

Hope this makes sense. Any feedback would be very helpful. Thanks!

Eric

**Comment by epaulz-vt** [comment]
Thank you... I will experiment with that method.

As a follow-up question, what would be the best way to have a function within the plugin run just once at the beginning of the simulation, but not run again after n timesteps?  E.g. a function called train_agent() to be called when Bluesky initializes with a scenario.  The function runs as long as the simulation is running, and within it runs x number of episodes.  It seems I can only tell a function to run periodically (e.g. every 5 seconds) but not just "run it once as soon as the plugin initializes".  If I try to run something before returning the plugin config, then my plugin code runs but the simulation is blocked until the plugin is finished running.

Thanks,
Eric

**Comment by jooste** [comment]
Hi Eric,

In addition to periodic functions you can also define new stack functions in your plugin. You can then call this function once at the beginning of each scenario file.

To add to your previous question: if bluesky and your RL code are running asynchronously and you want to ensure that the simulation waits for the RL agent to send a new command you can use the SCHEDULE and DELAY commands. For instance, doing 

DELAY 10 HOLD

would tell the simulation to pause after 10 seconds simulation time. You could do the same for a custom stack function you define.

Cheers,
Joost

**Comment by epaulz-vt** [comment]
Great, I think this information should allow me to do what I'm planning.  Thank you!
