### ISSUE TITLE
Autopilot performs unecessary HDG changes when navigating waypoints in a staight line

### ISSUE THREAD

**Issue by andubadea** [TUDelft-CNS-ATM/bluesky#271]
After passing a waypoint, the aircraft in the attached scenario performs a small unnecessary heading change before resuming navigation towards the next waypoint. This is undesirable behaviour, especially if constant SPD MVP is used, as maintaining the heading can lead to undesirable routing.

![OVw8ZXHZM5](https://user-images.githubusercontent.com/37139260/114697857-136b0c00-9d27-11eb-9ee4-431056cfc9b6.gif)

This occurs when using a DJI Matrice 600 rotorcraft on a small scale (urban) area. 

[M2_test_1.scn.txt](https://github.com/TUDelft-CNS-ATM/bluesky/files/6310224/M2_test_1.scn.txt)

**Comment by ProfHoekstra** [comment]
Thanks, especially for adding the scn file, which in general helps a lot!

It seems to be due to low speeds creating a very low turndist criterium used, which is then missed (may even be laterally). This will be adapted as part of the AP update(s). Seems to point to the same problem of waypoint passing. Next to speed tuning, using the along leg distance to waypoint instead of actual distance (so the dot product divided by leg length) hopefully also solves this one in the first update.

**Comment by ProfHoekstra** [comment]
Fixed wobble during waypoint passing. 

Cause was asynchronous scheduling of different parts of autopilot to save CPU time, but later qdr,dist calculation (most time expensive part) was updated anyway. As a result the gain was less and this caused the wobble as well. 

Solution: always run autopilot update function synchronous with guidance part of FMS unit for now.

Option to schedule parts of A/P not completely removed: Might also be tied to a command in the future to set scheduling.
