### ISSUE TITLE
ADDWPT missing WPTs after turn

### ISSUE THREAD

**Issue by Ellislee1** [TUDelft-CNS-ATM/bluesky#286]
I am playing around with some functions and I can't tell if it is meant to do this: 
* Create an aircraft `CRE AC1 A321 52.183115,-3.736687 360 FL320 300`
* `ADDWPT AC1 WPL`
* `ADDWPT AC1 SLP`
* `ADDWPT AC1 TNT`
* `ADDWPT AC1 SH`
* `ADDWPT AC1 BCN`
* `ADDWPT AC1 GOS`
* `ADDWPT AC1 NN`
* `ADDWPT AC1 WIT`
* `ADDWPT AC1 LE`
* `ADDWPT AC1 LIC`
After running the sim The aircraft makes a turn around 25nm from TNT and ignores the WPTs SH, BCN and GOS. I also tested it with shorter routes and attatched the images below. Any Ideah how to solve this issue?

![image](https://user-images.githubusercontent.com/29206618/118531504-cfac5d80-b73d-11eb-9250-703166f27499.png)
![image](https://user-images.githubusercontent.com/29206618/118532117-7e509e00-b73e-11eb-931e-c68dbe449a71.png)
![image](https://user-images.githubusercontent.com/29206618/118532247-a6d89800-b73e-11eb-8004-0882c0b2deb9.png)

**Comment by ProfHoekstra** [comment]
Dear Ellis,

Thanks for reporting this. Yes, I noticed similar behaviour of too eager waypoint switching too. It appears this has to do with the negative radial speed (range rate) relative to an active waypoint. This criterion was added due to some logic made for the small scale and low speed of UAVs to avoid missing passed waypoints.

I also have a fix for it in preparation, but this has not yet been finished & tested. Will be merged in the master version in the coming days. This should also fix the behaviour of your example.

Best regards,
    Jacco Hoekstra

From: Ellis Thompson ***@***.***>
Sent: maandag 17 mei 2021 19:36
To: TUDelft-CNS-ATM/bluesky ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [TUDelft-CNS-ATM/bluesky] ADDWPT missing WPTs after turn (#286)


I am playing around with some functions and I can't tell if it is meant to do this:

  *   Create an aircraft CRE AC1 A321 52.183115,-3.736687 360 FL320 300
  *   ADDWPT AC1 WPL
  *   ADDWPT AC1 SLP
  *   ADDWPT AC1 TNT
  *   ADDWPT AC1 SH
  *   ADDWPT AC1 BCN
  *   ADDWPT AC1 GOS
  *   ADDWPT AC1 NN
  *   ADDWPT AC1 WIT
  *   ADDWPT AC1 LE
  *   ADDWPT AC1 LIC
After running the sim The aircraft makes a turn around 25nm from TNT and ignores the WPTs SH, BCN and GOS. I also tested it with shorter routes and attatched the images below. Any Ideah how to solve this issue?

[image]<https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_29206618_118531504-2Dcfac5d80-2Db73d-2D11eb-2D9250-2D703166f27499.png&d=DwMCaQ&c=XYzUhXBD2cD-CornpT4QE19xOJBbRy-TBPLK0X9U2o8&r=5JxzVuDw_d0JV-kYyto54d3K2zKNIvniSIeVeSDtif4&m=unFQ5bTHmp_y0GomhpQDnNp2EBB0WQyo3S4oSLgFcQw&s=Ep5lB7ljEWGeu9IEJJJJVd0q-0r9IUkyKoFRKIKcoeU&e=>
[image]<https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_29206618_118532117-2D7e509e00-2Db73e-2D11eb-2D931e-2Dc68dbe449a71.png&d=DwMCaQ&c=XYzUhXBD2cD-CornpT4QE19xOJBbRy-TBPLK0X9U2o8&r=5JxzVuDw_d0JV-kYyto54d3K2zKNIvniSIeVeSDtif4&m=unFQ5bTHmp_y0GomhpQDnNp2EBB0WQyo3S4oSLgFcQw&s=usa8Od4Jgriil0Ay4k5EKk3L--_3S9F1jq_B5UPQrWs&e=>
[image]<https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_29206618_118532247-2Da6d89800-2Db73e-2D11eb-2D8004-2D0882c0b2deb9.png&d=DwMCaQ&c=XYzUhXBD2cD-CornpT4QE19xOJBbRy-TBPLK0X9U2o8&r=5JxzVuDw_d0JV-kYyto54d3K2zKNIvniSIeVeSDtif4&m=unFQ5bTHmp_y0GomhpQDnNp2EBB0WQyo3S4oSLgFcQw&s=2Nec5S2Papmeb74XJ0VGVKd8S-xXwGMpJlxgqUDndP0&e=>

**Comment by ProfHoekstra** [comment]
Dear Ellis,

P.S. A temporary fix can be to disable the "away" switch in actwpdata.py line 68 (e.g. away = False).

**Comment by Ellislee1** [comment]
Thanks @ProfHoekstra!

**Comment by ProfHoekstra** [comment]
Fixed by making only using "you've passed it as you are flying away from the active wp"-switch only when in a 4-second vicinity of waypoint, so it scales using the ground speed. See below effect on example flight plan.

![temp](https://user-images.githubusercontent.com/7159044/119217263-5d3ed300-bad9-11eb-9060-819ba5c5fa59.png)
