### ISSUE TITLE
[Enhancement] Replaceable "aporasas" class

### ISSUE THREAD

**Issue by andubadea** [TUDelft-CNS-ATM/bluesky#300]
Would it be possible to make the aporasas class replaceable? This would open the opportunity to create custom velocity switching plugins past the choice between autopilot and conflict resolution.

An example of this could be velocity logic that is applied differently when a merging state is detected (in drones for example).

**Comment by ProfHoekstra** [comment]
Why not simply use a plug-in that issues SPD commands? You can leave LNAV and even VNAV on. A speed command while in VNAV will switch off the speed part of VNAV.

**Comment by malikdoole** [comment]
It is possible to use a plug-in that issues SPD commands for a given condition. However, it does not switch back to the autopilot speed once the condition is false.

**Comment by ProfHoekstra** [comment]
It could. You could easily do that in the plug-in, by saving the selected value in a recovery speed when issuing the SPD command, or in case of VNAV, issue a "VNAV ON" which will also enable the speed part of VNAV if that's what your using.

This would have exactly the same effect and allows you to do this without the need for duplicating parts of the existing autopilot and will still work after future updates or extensions of the autopilot. you can also do this on a per vehicle basis if you do it in the plug-in.

It is also a more appropriate way to do it, as merging is more of a "higher order" type of behaviour, which should feed the speed-mode of the autopilot. That's why these kind of actions are usually dealt with in plug-ins.

**Comment by malikdoole** [comment]
That would work. Thank you @ProfHoekstra.
