### ISSUE TITLE
Aircrafts occasionally deviates immensely from path when using MVP with SPD resolution

### ISSUE THREAD

**Issue by andersmh** [TUDelft-CNS-ATM/bluesky#349]
When using the MVP algorithm, with the horizontal SPD value and no vertical resolution, I get some weird behavior, which can be seen in the video below. 

The aircrafts are generated in the initial circle and will follow the path provided to their destination within the other circle area. 

However, sometimes, the conflict resolution algorithm accelerates the aircrafts immensely forward, and they will go in a straight line past the waypoint they were supposed to fly over. This mainly happens for larger clusters, however, it also occurs when only two aircrafts are in conflict.

Not sure if this is a parameter issue on my end, or if it is the algorithm itself. However, it seems to be an issue with the algorithm.

The scenario file, code prints output in cmd, and a video are appended.

https://user-images.githubusercontent.com/31239471/145422458-9dc230b0-b6eb-4a02-acce-2a36f499d870.mp4

![Screenshot 2021-12-09 160941](https://user-images.githubusercontent.com/31239471/145422485-b6d6efe5-0384-43df-8ceb-9999b1e7c8f1.png)

[MVP_SPD.txt](https://github.com/TUDelft-CNS-ATM/bluesky/files/7686337/MVP_SPD.txt)

**Comment by MiGiliam** [comment]
Hi Anders,

I think your issue with UAVs flying in straight lines past the waypoints they were supposed to fly over comes from the way the autopilot (waypoint following) and conflict resolution are implemented in BlueSky. Conflicts are prioritized over the autopilot. This means that the autopilot is ignored when conflict resolution is active for an aircraft.

In case of the cluster consisting of UAV15, UAV16, and UAV18: although the initial conflicts are resolved, the conflict resolution (CR) module stays active to make sure the UAVs stay on their "resolution paths" until it is safe to resume normal navigation (waypoint following). Whether CR stays active is determined in bluesky/traffic/asas/resolution.py in the ```resumenav``` function starting on line 108. Three criteria are used:
1. Whether the aircraft pair has passed the closest point of approach: only switch off CR when the aircraft have actually passed each other (otherwise the same conflict would be triggered again).
2. Whether the aircraft are in a horizontal loss of separation: do not switch off CR when the separation minima are being violated at the moment.
3. Whether the aircarft are in a "bouncing" conflict: do not switch off CR if they continuously get in and out of conflict due to a small difference in heading.

Printing whether conflict resolution is active confirms that for UAV15, UAV16, and UAV18 the conflict resolution module is active while they are flying past the waypoints (see the figure below). Try deleting two of the three UAVs in the cluster and you will see that the other immediately resumes normal navigation and flies towards the waypoint.
![APorASAS](https://user-images.githubusercontent.com/26272893/145558428-b1d697e4-933f-4542-b6c9-f05d2883f97e.png)

Furthermore, I think the UAVs all speed up due to the complexity of the conflict in combination with the speed only constraint. Only allowing a speed change significantly reduces the options for resolution maneuvers. Furthermore, at the time the three aircraft speed up, the trailing UAV18 also seems to be resolving a conflict with UAV20 using a speed increase. Since MVP works by summing the separate resolution maneuvers of all simultaneous pairwise conflicts, the speed up of UAV18 from conflict (UAV18, UAV20) forces UAV18 to continue flying fast towards UAV15 and UAV16. Consequently, UAV15 and UAV16 will also speed up in order to avoid UAV18. Neverthelss, I am not entirely sure about this so you should check the speed changes from the resolution module if you want to know what happens exactly. Although the resolution module works with simple rules, complex patterns can emerge due to interactions between the aircraft in the simulation.

\
\
\
\
PS. If you are interested, you can find the update sequence of the functions related to simulation of traffic in bluesky/traffic/traffic.py, . Check out line 404-407 (in the traffic ```update``` function):
```
#---------- Fly the Aircraft --------------------------
self.ap.update()  # Autopilot logic
self.update_asas()  # Airborne Separation Assurance
self.aporasas.update()   # Decide to use autopilot or ASAS for commands
```
As can be seen, autopilot (AP) logic is updated first. This is followed by the ASAS module, performing both conflict detection and conflict resolution. Since the AP and ASAS can have different update rates (by default the autopilot updates more frequently), it is necessary that the APorASAS module determines whether conflict resolution is active. This prevents the autopilot from overriding a conflict resolution maneuver at simulation steps where the ASAS module does not update. Depending on whether conflict resolution (CR) is active (True or False), it chooses between the AP or ASAS output of ```trk```, ```tas```, ```alt```, and ```vs``` per aircraft. This is done in bluesky/traffic/aporasas.py, see lines 39-42.
