### ISSUE TITLE
Remove aircraft on route completion

### ISSUE THREAD

**Issue by Ellislee1** [TUDelft-CNS-ATM/bluesky#418]
I'm importing bluesky as a python package, assigning a route through the stack command. Is there an easy way to check to see if an aircraft has reached its final way point and then delete it from the sim?

```python
def add_aircraft(...):
        ...  
        bs.traf.cre(acid=f"{_id}", actype="AMZN", aclat=start_position[0],
                    aclon=start_position[1], achdg=start_position[3], acalt=start_position[2]/m,
                    acspd=instart_positionit[4]/ms)

        for wpt in wpts:  # add the target waypoints
            self.append_waypoint(_id, wpt)

def append_waypoint(self, _id, wpt):
        bs.stack.stack(f'ADDWPTMODE {_id} FLYOVER')
        bs.stack.stack(f'ADDWPT {_id} {wpt["lat"]} {wpt["lon"]} {wpt["alt"]}')
```

**Comment by ProfHoekstra** [comment]
Dear Ellis,

Yes, there are several ways:


-        Check whether the index of the active waypoint (iacwpt) is equal to the number of waypoint (nwp).

-        Check the distance to the final waypoint

-        Maybe even by checking whether LNAV has been switched off because of passing the last waypoint, but that is very scenario dependent and less secure

Hope this helps.

Best regards,
    Jacco Hoekstra

From: Ellis Thompson ***@***.***>
Sent: donderdag 25 augustus 2022 18:33
To: TUDelft-CNS-ATM/bluesky ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [TUDelft-CNS-ATM/bluesky] Remove aircraft on route completion (Issue #418)


I'm importing bluesky as a python package, assigning a route through the stack command. Is there an easy way to check to see if an aircraft has reached its final way point and then delete it from the sim?

def add_aircraft(...):

        ...

        bs.traf.cre(acid=f"{_id}", actype="AMZN", aclat=start_position[0],

                    aclon=start_position[1], achdg=start_position[3], acalt=start_position[2]/m,

                    acspd=instart_positionit[4]/ms)



        for wpt in wpts:  # add the target waypoints

            self.append_waypoint(_id, wpt)



def append_waypoint(self, _id, wpt):

        bs.stack.stack(f'ADDWPTMODE {_id} FLYOVER')

        bs.stack.stack(f'ADDWPT {_id} {wpt["lat"]} {wpt["lon"]} {wpt["alt"]}')

**Comment by ProfHoekstra** [comment]
To delete it or log it or do any stack command, you can use the AT command with the destination waypoint.

From: Ellis Thompson ***@***.***>
Sent: donderdag 25 augustus 2022 18:33
To: TUDelft-CNS-ATM/bluesky ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [TUDelft-CNS-ATM/bluesky] Remove aircraft on route completion (Issue #418)


I'm importing bluesky as a python package, assigning a route through the stack command. Is there an easy way to check to see if an aircraft has reached its final way point and then delete it from the sim?

def add_aircraft(...):

        ...

        bs.traf.cre(acid=f"{_id}", actype="AMZN", aclat=start_position[0],

                    aclon=start_position[1], achdg=start_position[3], acalt=start_position[2]/m,

                    acspd=instart_positionit[4]/ms)



        for wpt in wpts:  # add the target waypoints

            self.append_waypoint(_id, wpt)



def append_waypoint(self, _id, wpt):

        bs.stack.stack(f'ADDWPTMODE {_id} FLYOVER')

        bs.stack.stack(f'ADDWPT {_id} {wpt["lat"]} {wpt["lon"]} {wpt["alt"]}')
