### ISSUE TITLE
[Suggestion] Development brach

### ISSUE THREAD

**Issue by andubadea** [TUDelft-CNS-ATM/bluesky#431]
BlueSky is in need of a development branch, with the master branch being updated only periodically after all the changes have been tested and accepted. 

The changes that are tested can then be merged into the main branch.

**Comment by ProfHoekstra** [comment]
Yes, but with a slight difference. Instead of a general "development branch", it is better to use a system like releases. This addresses the same issue. 

Explanation: 
In practice most of the times you want the latest version, because of some bug fix or modification. So calling it development branch is strange as it will be the most often used. But if you need a thoroughly tested, stable version that is not changed during your experiment, you can take a (initially the latest) release and stick to it

An added benefit is that by having the previous releases available  you can keep using an older release for compatibility or if you're not interested in new features.
