### ISSUE TITLE
Scenario not working properly

### ISSUE THREAD

**Issue by eminb61** [TUDelft-CNS-ATM/bluesky#460]
I'm running the below scenario. However, the aircraft keeps the same heading and never stops at EHBK. 

0:00:00.00> pan eham
0:00:00.00>CRE KL204,A320,EHAM,RWY18L,,0,0
0:00:00.00>TRAIL ON
0:00:00.00>ORIG KL204 EHAM RWY18L
#0:00:00.00>DEST KL204 EHBK RWY21
0:00:00.00>KL204 VNAV on
0:00:00.00>SPD KL204 250
0:00:00.00>ALT KL204 3000
0:00:00.00>ADDWPT KL204 NV
0:00:00.00>ADDWPT KL204 RR, FL50
0:00:00.00>ADDWPT KL204 EHN, 3000
0:00:00.00>ADDWPT KL204 ZL006, 1000,180
0:00:00.00>DEST KL204 EHBK RWY21

In the below case, the aircraft stops at EHBK but the take-off process is problematic. The altitude stays constant at 0 until it reaches the first waypoint. Then goes up to 3000.

0:00:00.00> pan eham
0:00:00.00>CRE KL204,A320,EHAM,RWY18L,,0,0
0:00:00.00>TRAIL ON
0:00:00.00>ORIG KL204 EHAM RWY18L
0:00:00.00>DEST KL204 EHBK RWY21
0:00:00.00>SPD KL204 250
0:00:00.00>ALT KL204 3000
0:00:00.00>ADDWPT KL204 NV
0:00:00.00>ADDWPT KL204 RR, FL50
0:00:00.00>ADDWPT KL204 EHN, 3000
0:00:00.00>ADDWPT KL204 ZL006, 1000,180
0:00:00.00>KL204 VNAV on

The below case works as intended:
0:00:00.00> pan eham
0:00:00.00>CRE KL204,A320,EHAM,RWY18L,,0,0
0:00:00.00>TRAIL ON
0:00:00.00>ORIG KL204 EHAM RWY18L
0:00:00.00>KL204 VNAV on
0:00:00.00>SPD KL204 250
0:00:00.00>ALT KL204 3000
0:00:00.00>ADDWPT KL204 NV
0:00:00.00>ADDWPT KL204 RR, FL50
0:00:00.00>ADDWPT KL204 EHN, 3000
0:00:00.00>ADDWPT KL204 ZL006, 1000,180
0:00:00.00>DEST KL204 EHBK RWY21
0:20:00.00>KL204 VNAV on

**Comment by ProfHoekstra** [comment]
Ok, we’ll check this case. Thank you for including the scenario!

Best regards/Met vriendelijke groeten,
    Jacco Hoekstra


On 16 Apr 2023, at 22:41, eminb61 ***@***.***> wrote:

﻿

I'm running the below scenario. However, the aircraft keeps the same heading and never stops at EHBK.

0:00:00.00> pan eham
0:00:00.00>CRE KL204,A320,EHAM,RWY18L,,0,0
0:00:00.00>TRAIL ON
0:00:00.00>ORIG KL204 EHAM RWY18L
#0:00:00.00>DEST KL204 EHBK RWY21
0:00:00.00>KL204 VNAV on
0:00:00.00>SPD KL204 250
0:00:00.00>ALT KL204 3000
0:00:00.00>ADDWPT KL204 NV
0:00:00.00>ADDWPT KL204 RR, FL50
0:00:00.00>ADDWPT KL204 EHN, 3000
0:00:00.00>ADDWPT KL204 ZL006, 1000,180
0:00:00.00>DEST KL204 EHBK RWY21

In the below case, the aircraft stops at EHBK but the take-off process is problematic. The altitude stays constant at 0 until it reaches the first waypoint. Then goes up to 3000.

0:00:00.00> pan eham
0:00:00.00>CRE KL204,A320,EHAM,RWY18L,,0,0
0:00:00.00>TRAIL ON
0:00:00.00>ORIG KL204 EHAM RWY18L
0:00:00.00>DEST KL204 EHBK RWY21
0:00:00.00>SPD KL204 250
0:00:00.00>ALT KL204 3000
0:00:00.00>ADDWPT KL204 NV
0:00:00.00>ADDWPT KL204 RR, FL50
0:00:00.00>ADDWPT KL204 EHN, 3000
0:00:00.00>ADDWPT KL204 ZL006, 1000,180
0:00:00.00>KL204 VNAV on

**Comment by ProfHoekstra** [comment]
When running the scenarios, the first one seems to run fine. It never arrives at EHBK because the destination line is commented out. So it follows the route until EHN and then keeps its heading. You do get an error for activating VNAV too soon. This will not do anything. therefore the ALT command will work and ti will stay at 3000 ft, as should be expected. 

In the second one, the only thing I see is it seems the zero altitude of the runway is kept too long. It can be fixed by adding an altitude 3000 ft constraint at NV.  Normally the first point after take-off indicates the altitude for the initial climb.
The reason it does not climb is that the competing ALT command and VNAV command are at the same time instance. This means the ref altitude does not reach and get activated in the autopilot as it is immediately overridden by the VNAV command. If your a/c climbs too late or too slow, it will not be able to reach 5000 ft at RR, so it tries to keep the reached altitude at the end of the climb at RR. But the best would be to use "ADDWPT NV 3000"

In the third one, the strange thing I see, its that you override your ALT command at the same time stamp by a VNAV afterwards, thereby making the ALT command useless. VNAV is an alternative AP mode to SPD select and ALT select. 
 
So the main thing is to avoid using VNAV and ALT/SPD command at the same time step as they cancel each other out and last one will be the one that is used.  SPD after VNAV only cancels VNAVSPD so it will still follow the altitude profile.
