### ISSUE TITLE
Scenario Files Not Working as Intended

### ISSUE THREAD

**Issue by AdityaIshaanT** [TUDelft-CNS-ATM/bluesky#469]
Hello! 

I am trying to automate the creation of scenario files from ADS-B data to simulate real flights and analyze their fuel flow and emissions. The scenario file below has been created through a Python script.   

I have been trying to make it work but it keeps giving me trouble. Upon running it, the speed of the aircraft goes on decreasing until a certain value and then stays constant while in cruise. It does not follow the speed constraints defined at the waypoints. 

For reference, the altitude constraints are working as intended. Also, I am using BADA Performance Data with the required files added to the bluesky -> resources -> performance -> BADA folder. 

Appreciate your guidance and help in this matter. 

Looking forward to hearing from you and thanking you in anticipation.

Best Regards,
Aditya Ishaan. T

00:00:00.00> TRAIL ON
00:00:00.00> CRELOG AAR751_LOG 1
00:00:00.00> AAR751_LOG ADD traf.lat, traf.lon, traf.alt, traf.perf.fuelflow
00:00:00.00> AAR751_LOG ON

00:00:00.00> CRE AAR751, A359, 13.312728870660068, 113.7190088443458, 198.6712646484375, 40000.0, 459.0087890625
00:00:00.00> ADDWPT AAR751, 13.308837823569776, 113.71768282726408, 40000.0, 459.0087890625
00:00:00.00> ADDWPT AAR751, 12.881981693208218, 113.56933588162065, 40000.0, 458.7890625
00:00:00.00> ADDWPT AAR751, 12.564651388674974, 113.45008051022889, 40000.0, 462.5244140625
00:00:00.00> ADDWPT AAR751, 12.215515114367008, 113.17196544259788, 40000.0, 466.9189453125
00:00:00.00> ADDWPT AAR751, 11.901219226419926, 112.7197746746242, 40000.0, 467.578125
00:00:00.00> ADDWPT AAR751, 11.643401943147182, 112.35026383772492, 40000.0, 471.7529296875
00:00:00.00> ADDWPT AAR751, 11.335967984050512, 111.9122314453125, 40000.0, 478.125
00:00:00.00> ADDWPT AAR751, 10.983489844948052, 111.412353515625, 40000.0, 480.76171875
00:00:00.00> ADDWPT AAR751, 10.698402374982834, 111.0097623243928, 40000.0, 481.4208984375
00:00:00.00> ADDWPT AAR751, 10.405728612095118, 110.59794450178742, 40000.0, 474.169921875
00:00:00.00> ADDWPT AAR751, 10.131070408970118, 110.27346896007656, 40000.0, 468.896484375
00:00:00.00> ADDWPT AAR751, 9.672592040151358, 109.94977528229356, 40000.0, 468.2373046875
00:00:00.00> ADDWPT AAR751, 9.30207822471857, 109.68931552022696, 40000.0, 471.09375
00:00:00.00> ADDWPT AAR751, 8.892734237015247, 109.40242359414697, 40000.0, 474.8291015625
00:00:00.00> ADDWPT AAR751, 8.45486395061016, 109.09783713519572, 40000.0, 472.1923828125
00:00:00.00> ADDWPT AAR751, 8.09417724609375, 108.84788375347853, 40000.0, 475.048828125
00:00:00.00> ADDWPT AAR751, 7.650512550026178, 108.54110458865762, 40000.0, 475.927734375
00:00:00.00> ADDWPT AAR751, 7.30558231472969, 108.30312794074416, 40000.0, 473.0712890625
00:00:00.00> ADDWPT AAR751, 6.993356421589851, 108.0874265357852, 40000.0, 472.412109375
00:00:00.00> ADDWPT AAR751, 6.601805537939072, 107.81461503356697, 40000.0, 476.1474609375
00:00:00.00> ADDWPT AAR751, 6.298782303929329, 107.6040079817176, 40000.0, 478.3447265625
00:00:00.00> ADDWPT AAR751, 6.040191538631916, 107.4245024845004, 40000.0, 478.3447265625
00:00:00.00> ADDWPT AAR751, 5.6920817121863365, 107.18318531289697, 40000.0, 479.2236328125
00:00:00.00> ADDWPT AAR751, 5.406949315220118, 106.98576299473643, 40000.0, 482.080078125
00:00:00.00> ADDWPT AAR751, 5.098434425890446, 106.77244540303946, 40000.0, 489.990234375
00:00:00.00> ADDWPT AAR751, 4.786175172775984, 106.55682262033224, 40000.0, 491.5283203125
00:00:00.00> ADDWPT AAR751, 4.451138768345118, 106.32563615217803, 40000.0, 489.990234375
00:00:00.00> ADDWPT AAR751, 4.162994250655174, 106.0588926449418, 40000.0, 496.142578125
00:00:00.00> ADDWPT AAR751, 3.975402731448412, 105.8281797543168, 40000.0, 491.30859375
00:00:00.00> ADDWPT AAR751, 3.7885893881320953, 105.59835132211448, 40000.0, 491.30859375
00:00:00.00> ADDWPT AAR751, 3.576887659728527, 105.33729275688528, 40000.0, 490.6494140625
00:00:00.00> ADDWPT AAR751, 3.424708340317011, 105.14962546527386, 39625.0, 487.79296875
00:00:00.00> ADDWPT AAR751, 3.421729076653719, 105.14593189582229, 39600.0, 487.79296875
00:00:00.00> ADDWPT AAR751, 3.2141525857150555, 104.89012090489268, 35125.0, 477.0263671875
00:00:00.00> ADDWPT AAR751, 3.024731632322073, 104.65869756415486, 30825.0, 454.833984375
00:00:00.00> ADDWPT AAR751, 2.825317271053791, 104.44599721580744, 26700.0, 431.54296875
00:00:00.00> ADDWPT AAR751, 2.6503141969442368, 104.25876410678028, 22950.0, 420.7763671875
00:00:00.00> ADDWPT AAR751, 2.4682461842894554, 104.10483514890076, 20675.0, 358.8134765625
00:00:00.00> ADDWPT AAR751, 2.241302467882633, 104.10220893099904, 17700.0, 336.181640625
00:00:00.00> ADDWPT AAR751, 2.0522001944482327, 104.0350341796875, 15800.0, 284.326171875
00:00:00.00> ADDWPT AAR751, 1.8784788809716704, 104.02698051184416, 13100.0, 279.931640625
00:00:00.00> ADDWPT AAR751, 1.7059020325541496, 104.07167064025998, 10475.0, 273.1201171875
00:00:00.00> ADDWPT AAR751, 1.5314754657447338, 104.10701343789697, 7975.0, 264.7705078125
00:00:00.00> ADDWPT AAR751, 1.34191470220685, 104.11113331094384, 6975.0, 238.623046875
00:00:00.00> ADDWPT AAR751, 1.1991390399634838, 104.05208179727197, 4550.0, 231.15234375
00:00:00.00> ADDWPT AAR751, 1.1523284576833248, 103.93448118120432, 2975.0, 185.2294921875
00:00:00.00> ADDWPT AAR751, 1.2774810008704662, 103.94728319719434, 1575.0, 161.279296875
00:00:00.00> ADDWPT AAR751, 1.3528747111558914, 103.97907827049494, 100.0, 138.427734375
00:00:00.00> AAR751 VNAV ON
00:00:00.00> AAR751 AT AAR751048 DO AAR751_LOG OFF
00:00:00.00> AAR751 AT AAR751048 DO DEL AAR751

![image](https://github.com/TUDelft-CNS-ATM/bluesky/assets/127282921/00a10ac2-e45e-4e9e-ad8d-c929a9c45a39)

![image](https://github.com/TUDelft-CNS-ATM/bluesky/assets/127282921/d11d0617-6f2c-47ff-8e05-e092566c2815)

**Comment by ProfHoekstra** [comment]
Hi Aditya,

From first glance, maybe it is caused by  the extremely short legs. Meaning the aircraft is constantly in turning/wp switch mode. Speeds as FROM speeds, which will be active on the leg after the waypoint after the turn.

Best regards,
    Jacco Hoekstra

From: AdityaIshaanT ***@***.***>
Sent: vrijdag 23 juni 2023 09:32
To: TUDelft-CNS-ATM/bluesky ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [TUDelft-CNS-ATM/bluesky] Scenario Files Not Working as Intended (Issue #469)


Hello!

I am trying to automate the creation of scenario files from ADS-B data to simulate real flights and analyze their fuel flow and emissions. The scenario file below has been created through a Python script.

I have been trying to make it work but it keeps giving me trouble. Upon running it, the speed of the aircraft goes on decreasing until a certain value and then stays constant while in cruise. It does not follow the speed constraints defined at the waypoints.

For reference, the altitude constraints are working as intended. Also, I am using BADA Performance Data with the required files added to the bluesky -> resources -> performance -> BADA folder.

Appreciate your guidance and help in this matter.

Looking forward to hearing from you and thanking you in anticipation.

Best Regards,
Aditya Ishaan. T

00:00:00.00> TRAIL ON
00:00:00.00> CRELOG AAR751_LOG 1
00:00:00.00> AAR751_LOG ADD traf.lat, traf.lon, traf.alt, traf.perf.fuelflow
00:00:00.00> AAR751_LOG ON

00:00:00.00> CRE AAR751, A359, 13.312728870660068, 113.7190088443458, 198.6712646484375, 40000.0, 459.0087890625
00:00:00.00> ADDWPT AAR751, 13.308837823569776, 113.71768282726408, 40000.0, 459.0087890625
00:00:00.00> ADDWPT AAR751, 12.881981693208218, 113.56933588162065, 40000.0, 458.7890625
00:00:00.00> ADDWPT AAR751, 12.564651388674974, 113.45008051022889, 40000.0, 462.5244140625
00:00:00.00> ADDWPT AAR751, 12.215515114367008, 113.17196544259788, 40000.0, 466.9189453125
00:00:00.00> ADDWPT AAR751, 11.901219226419926, 112.7197746746242, 40000.0, 467.578125
00:00:00.00> ADDWPT AAR751, 11.643401943147182, 112.35026383772492, 40000.0, 471.7529296875
00:00:00.00> ADDWPT AAR751, 11.335967984050512, 111.9122314453125, 40000.0, 478.125
00:00:00.00> ADDWPT AAR751, 10.983489844948052, 111.412353515625, 40000.0, 480.76171875
00:00:00.00> ADDWPT AAR751, 10.698402374982834, 111.0097623243928, 40000.0, 481.4208984375
00:00:00.00> ADDWPT AAR751, 10.405728612095118, 110.59794450178742, 40000.0, 474.169921875
00:00:00.00> ADDWPT AAR751, 10.131070408970118, 110.27346896007656, 40000.0, 468.896484375
00:00:00.00> ADDWPT AAR751, 9.672592040151358, 109.94977528229356, 40000.0, 468.2373046875
00:00:00.00> ADDWPT AAR751, 9.30207822471857, 109.68931552022696, 40000.0, 471.09375
00:00:00.00> ADDWPT AAR751, 8.892734237015247, 109.40242359414697, 40000.0, 474.8291015625
00:00:00.00> ADDWPT AAR751, 8.45486395061016, 109.09783713519572, 40000.0, 472.1923828125
00:00:00.00> ADDWPT AAR751, 8.09417724609375, 108.84788375347853, 40000.0, 475.048828125
00:00:00.00> ADDWPT AAR751, 7.650512550026178, 108.54110458865762, 40000.0, 475.927734375
00:00:00.00> ADDWPT AAR751, 7.30558231472969, 108.30312794074416, 40000.0, 473.0712890625
00:00:00.00> ADDWPT AAR751, 6.993356421589851, 108.0874265357852, 40000.0, 472.412109375
00:00:00.00> ADDWPT AAR751, 6.601805537939072, 107.81461503356697, 40000.0, 476.1474609375
00:00:00.00> ADDWPT AAR751, 6.298782303929329, 107.6040079817176, 40000.0, 478.3447265625
00:00:00.00> ADDWPT AAR751, 6.040191538631916, 107.4245024845004, 40000.0, 478.3447265625
00:00:00.00> ADDWPT AAR751, 5.6920817121863365, 107.18318531289697, 40000.0, 479.2236328125
00:00:00.00> ADDWPT AAR751, 5.406949315220118, 106.98576299473643, 40000.0, 482.080078125
00:00:00.00> ADDWPT AAR751, 5.098434425890446, 106.77244540303946, 40000.0, 489.990234375
00:00:00.00> ADDWPT AAR751, 4.786175172775984, 106.55682262033224, 40000.0, 491.5283203125
00:00:00.00> ADDWPT AAR751, 4.451138768345118, 106.32563615217803, 40000.0, 489.990234375
00:00:00.00> ADDWPT AAR751, 4.162994250655174, 106.0588926449418, 40000.0, 496.142578125
00:00:00.00> ADDWPT AAR751, 3.975402731448412, 105.8281797543168, 40000.0, 491.30859375
00:00:00.00> ADDWPT AAR751, 3.7885893881320953, 105.59835132211448, 40000.0, 491.30859375
00:00:00.00> ADDWPT AAR751, 3.576887659728527, 105.33729275688528, 40000.0, 490.6494140625
00:00:00.00> ADDWPT AAR751, 3.424708340317011, 105.14962546527386, 39625.0, 487.79296875
00:00:00.00> ADDWPT AAR751, 3.421729076653719, 105.14593189582229, 39600.0, 487.79296875
00:00:00.00> ADDWPT AAR751, 3.2141525857150555, 104.89012090489268, 35125.0, 477.0263671875
00:00:00.00> ADDWPT AAR751, 3.024731632322073, 104.65869756415486, 30825.0, 454.833984375
00:00:00.00> ADDWPT AAR751, 2.825317271053791, 104.44599721580744, 26700.0, 431.54296875
00:00:00.00> ADDWPT AAR751, 2.6503141969442368, 104.25876410678028, 22950.0, 420.7763671875
00:00:00.00> ADDWPT AAR751, 2.4682461842894554, 104.10483514890076, 20675.0, 358.8134765625
00:00:00.00> ADDWPT AAR751, 2.241302467882633, 104.10220893099904, 17700.0, 336.181640625
00:00:00.00> ADDWPT AAR751, 2.0522001944482327, 104.0350341796875, 15800.0, 284.326171875
00:00:00.00> ADDWPT AAR751, 1.8784788809716704, 104.02698051184416, 13100.0, 279.931640625
00:00:00.00> ADDWPT AAR751, 1.7059020325541496, 104.07167064025998, 10475.0, 273.1201171875
00:00:00.00> ADDWPT AAR751, 1.5314754657447338, 104.10701343789697, 7975.0, 264.7705078125
00:00:00.00> ADDWPT AAR751, 1.34191470220685, 104.11113331094384, 6975.0, 238.623046875
00:00:00.00> ADDWPT AAR751, 1.1991390399634838, 104.05208179727197, 4550.0, 231.15234375
00:00:00.00> ADDWPT AAR751, 1.1523284576833248, 103.93448118120432, 2975.0, 185.2294921875
00:00:00.00> ADDWPT AAR751, 1.2774810008704662, 103.94728319719434, 1575.0, 161.279296875
00:00:00.00> ADDWPT AAR751, 1.3528747111558914, 103.97907827049494, 100.0, 138.427734375
00:00:00.00> AAR751 VNAV ON
00:00:00.00> AAR751 AT AAR751048 DO AAR751_LOG OFF
00:00:00.00> AAR751 AT AAR751048 DO DEL AAR751

**Comment by AdityaIshaanT** [comment]
Dear Prof. Hoekstra,

Thank you for your response. My apologies for the delay in getting back to you. Even upon significantly reducing the number of waypoints from 48 to about 11, the problem still persists. There is no change of speed during cruise when the altitude is constant. 

![image](https://github.com/TUDelft-CNS-ATM/bluesky/assets/127282921/6356ddcd-4931-4ab3-9447-a26af85eacf7)


Interestingly enough, the speed changes at the later waypoints at lower altitudes to reflect the constraint set at those waypoints. 

![image](https://github.com/TUDelft-CNS-ATM/bluesky/assets/127282921/c19d6ad8-44d0-452f-8fdc-88086e3012f8)

I was, therefore, wondering if there is some other issue at play here. Thank you once again for your guidance and time!

Best regards,
Aditya Ishaan. T

**Comment by jooste** [comment]
Hi @AdityaIshaanT!

The behaviour you are seeing is intentional! What you are seeing is performance limiting. The speed you are setting, 459 kts @ FL400 is equal to Mach 1.37, which is well beyond the capabilities of the A359 ;)

**Comment by AdityaIshaanT** [comment]
Now I finally see what the problem is. Really appreciate your help and guidance @ProfHoekstra and @jooste. Thank you so much!
